/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Car, Agency, User, Review, Notification } from "./types";

export const ALGERIAN_CITIES = [
  "الجزائر العاصمة",
  "باتنة",
  "وهران",
  "قسنطينة",
  "عنابة",
  "بجاية",
  "تلمسان",
  "سطيف"
];

export const CAR_TEMPLATES = [
  {
    brand: "بي إم دبليو",
    model: "BMW X7 M50i Extreme",
    category: "luxury" as const,
    transmission: "automatic" as const,
    seats: 7,
    fuel: "diesel" as const,
    pricePerDay: 28000,
    deposit: 60000,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=600",
    description: "بي إم دبليو X7 قمة الفخامة والرفاهية العائلية. تصميم هجومي ومقصورة مجهزة بأرقى التقنيات والجلود الطبيعية لكراء متميز في باتنة والشرق الجزائري."
  },
  {
    brand: "تسلا",
    model: "Tesla Model Y Performance",
    category: "luxury" as const,
    transmission: "automatic" as const,
    seats: 5,
    fuel: "essence" as const,
    pricePerDay: 22000,
    deposit: 50000,
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=600",
    description: "تسلا موديل واي الكهربائية بالكامل بأداء خارق. تسارع مذهل، القيادة الذاتية والمقصورة البسيطة العصرية توفر متعة كراء استثنائية."
  },
  {
    brand: "نيسان",
    model: "Nissan Kicks Active",
    category: "suv" as const,
    transmission: "automatic" as const,
    seats: 5,
    fuel: "essence" as const,
    pricePerDay: 11000,
    deposit: 25000,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600",
    description: "نيسان كيكس الرياضية الصغيرة مدمجة الحجم. قيادة رشيقة، استهلاك وقود ممتاز للغاية وارتفاع مناسب للشوارع والمسالك الجزائري."
  },
  {
    brand: "داسيا",
    model: "سانديرو ستيبواي (Sandero Stepway)",
    category: "economy" as const,
    transmission: "manual" as const,
    seats: 5,
    fuel: "diesel" as const,
    pricePerDay: 5500,
    deposit: 15000,
    image: "https://images.unsplash.com/photo-1532581291347-9c39cf10a73c?auto=format&fit=crop&q=80&w=600",
    description: "السيارة الأكثر شعبية وملاءمة لشوارع الجزائر. مزيج مثالي بين العلو المناسب على الطريق والاقتصاد الفائق في استهلاك الوقود."
  },
  {
    brand: "فولكس فاجن",
    model: "غولف 8 - Golf 8 R-Line",
    category: "luxury" as const,
    transmission: "automatic" as const,
    seats: 5,
    fuel: "essence" as const,
    pricePerDay: 13000,
    deposit: 40000,
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=600",
    description: "التصميم الرياضي والراحة القصوى مع أحدث التقنيات. مثالية للرحلات الفاخرة والمناسبات الخاصة في وهران والعاصمة."
  },
  {
    brand: "سيات",
    model: "إيبيزا - Ibiza FR",
    category: "economy" as const,
    transmission: "manual" as const,
    seats: 5,
    fuel: "essence" as const,
    pricePerDay: 7000,
    deposit: 20000,
    image: "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?auto=format&fit=crop&q=80&w=600",
    description: "سيارة شبابية بلمسة رياضية وأداء ممتاز في المدينة. اقتصادية وسهلة الركن."
  },
  {
    brand: "رونو",
    model: "سيمبول - Renault Symbol",
    category: "economy" as const,
    transmission: "manual" as const,
    seats: 5,
    fuel: "essence" as const,
    pricePerDay: 4800,
    deposit: 12000,
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600",
    description: "سيارة عائلية اقتصادية للغاية تتميز بمساحة خلفية واسعة للأمتعة وتكييف هواء قوي."
  },
  {
    brand: "تويوتا",
    model: "هايلوكس - Hilux Adventure 4x4",
    category: "suv" as const,
    transmission: "automatic" as const,
    seats: 5,
    fuel: "diesel" as const,
    pricePerDay: 18000,
    deposit: 50000,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600",
    description: "قوة الدفع الرباعي للرحلات الشاقة والصحراوية أو لتأمين الحضور القوي. سيارة مغامرة ممتازة."
  },
  {
    brand: "رانج روفر",
    model: "فيلار - Velar Premium",
    category: "luxury" as const,
    transmission: "automatic" as const,
    seats: 5,
    fuel: "diesel" as const,
    pricePerDay: 35000,
    deposit: 100000,
    image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=600",
    description: "الفخامة المطلقة للمناسبات أو الأعراس أو رحلات رجال الأعمال. مجهزة بأعلى مواصفات الرفاهية العالمية."
  },
  {
    brand: "هيونداي",
    model: "أكسنت - Hyundai Accent",
    category: "economy" as const,
    transmission: "automatic" as const,
    seats: 5,
    fuel: "essence" as const,
    pricePerDay: 6500,
    deposit: 15000,
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=600",
    description: "سلاسة في السياقة مع علبة التروس الأوتوماتيكية، موثوقية عالية وتوفير مثالي للوقود."
  }
];

export const INITIAL_AGENCIES: Agency[] = [
  {
    id: "agency_alger_ym",
    name: "وكالة اليمامة لكراء السيارات",
    logo: "https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=120",
    rating: 4.8,
    reviewsCount: 142,
    city: "الجزائر العاصمة",
    address: "04 شارع ديدوش مراد، الوسط، الجزائر العاصمة",
    phone: "0550 12 34 56",
    verified: true,
    banner: "https://images.unsplash.com/photo-1511527654041-421798efcf1a?auto=format&fit=crop&q=80&w=600",
    carsCount: 24
  },
  {
    id: "agency_oran_bahja",
    name: "البهجة للسيارات الفاخرة",
    logo: "https://images.unsplash.com/photo-1516841273335-e39b37888115?auto=format&fit=crop&q=80&w=120",
    rating: 4.9,
    reviewsCount: 98,
    city: "وهران",
    address: "نهج جيش التحرير الوطني (الواجهة البحرية)، وهران",
    phone: "0561 98 76 54",
    verified: true,
    banner: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=600",
    carsCount: 18
  },
  {
    id: "agency_const_bridges",
    name: "وكالة الجسور المعلقة للسيارات",
    logo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=120",
    rating: 4.6,
    reviewsCount: 75,
    city: "قسنطينة",
    address: "شارع قدور بومدوس، مقابل محطة التلفريك، قسنطينة",
    phone: "0552 45 67 89",
    verified: true,
    banner: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=600",
    carsCount: 12
  },
  {
    id: "agency_annaba_milano",
    name: "ميلانو رنت كار - عنابة",
    logo: "https://images.unsplash.com/photo-1557426131-08197764aa25?auto=format&fit=crop&q=80&w=120",
    rating: 4.7,
    reviewsCount: 54,
    city: "عنابة",
    address: "شارع طارق بن زياد، عنابة Centre",
    phone: "0540 88 99 00",
    verified: false,
    banner: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=600",
    carsCount: 9
  }
];

export const INITIAL_CARS: Car[] = [
  {
    id: "car_bmw_x7",
    brand: "بي إم دبليو",
    model: "BMW X7 M50i Extreme",
    year: 2026,
    category: "luxury",
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 28000,
    transmission: "automatic",
    city: "باتنة",
    agencyId: "agency_batna_auras",
    agencyName: "وكالة الأوراس لكراء السيارات",
    rating: 5.0,
    reviewsCount: 17,
    isAvailable: true,
    fuel: "diesel",
    seats: 7,
    deposit: 60000,
    description: "الأناقة والفخامة المطلقة لمركبة BMW X7 M50i في ولاية باتنة. متميزة للزفاف، مرافقة الوفود، والرحلات الفاخرة للوجهات السياحية."
  },
  {
    id: "car_tesla_y",
    brand: "تسلا",
    model: "Tesla Model Y Performance",
    year: 2026,
    category: "luxury",
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 22000,
    transmission: "automatic",
    city: "باتنة",
    agencyId: "agency_batna_auras",
    agencyName: "وكالة الأوراس لكراء السيارات",
    rating: 5.0,
    reviewsCount: 27,
    isAvailable: true,
    fuel: "electric",
    seats: 5,
    deposit: 50000,
    description: "تسلا موديل واي كهربائية رائدة ومريحة للغاية، متوفرة الآن للاستمتاع برحلة تكنولوجية صامتة وسلسة في شوارع باتنة."
  },
  {
    id: "car_nissan_kicks",
    brand: "نيسان",
    model: "Nissan Kicks Active",
    year: 2025,
    category: "suv",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 11000,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 4.9,
    reviewsCount: 18,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 25000,
    description: "نيسان كيكس الرشيقة والعملية للغاية لرحلات المدينة المزدحمة. سهلة التوجيه واقتصادية في استهلاك البنزين."
  },
  {
    id: "car_1",
    brand: "داسيا",
    model: "سانديرو ستيبواي - Stepway",
    year: 2024,
    category: "economy",
    image: "https://images.unsplash.com/photo-1532581291347-9c39cf10a73c?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 5500,
    transmission: "manual",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 4.8,
    reviewsCount: 46,
    isAvailable: true,
    fuel: "diesel",
    seats: 5,
    deposit: 15000,
    description: "سيارة داسيا ستيبواي مثالية وممتازة للتنقل في طرقات وسط العاصمة ومناطق تيبازة وبومرداس المحاذية. تأتي مع تكييف جيد جداً، ونظام صوتي بلوتوث."
  },
  {
    id: "car_2",
    brand: "فولكس فاجن",
    model: "غولف 8 - R line Sensation",
    year: 2024,
    category: "luxury",
    image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 14000,
    transmission: "automatic",
    city: "وهران",
    agencyId: "agency_oran_bahja",
    agencyName: "البهجة للسيارات الفاخرة",
    rating: 4.9,
    reviewsCount: 32,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 40000,
    description: "غولف 8 فئة R-Line الرياضية والفاخرة. فتحة سقف بانورامية، عداد ديجيتال، نظام اضاءة داخلي متعدد الألوان. مناسبة جدا للمناسبات ومحبّي المظهر الأنيق في الباهية وهران."
  },
  {
    id: "car_3",
    brand: "سيات",
    model: "إيبيزا FR - Ibiza",
    year: 2023,
    category: "economy",
    image: "https://images.unsplash.com/photo-1620891549027-942fdc95d3f5?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 7500,
    transmission: "manual",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 4.7,
    reviewsCount: 19,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 20000,
    description: "إيبيزا الشبابية بتشطيب فريد (FR). عجلات ألمنيوم مقاس 17، مقاعد رياضية وتحكم كامل على المقود. ممتازة في الأداء وتوفير البنزين."
  },
  {
    id: "car_4",
    brand: "تويوتا",
    model: "هايلوكس - Hilux Adventure 4x4",
    year: 2024,
    category: "suv",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 19000,
    transmission: "automatic",
    city: "قسنطينة",
    agencyId: "agency_const_bridges",
    agencyName: "وكالة الجسور المعلقة للسيارات",
    rating: 4.8,
    reviewsCount: 12,
    isAvailable: true,
    fuel: "diesel",
    seats: 5,
    deposit: 50000,
    description: "العملاق الياباني هايلوكس أدفنتشر بالدفع الرباعي. مثالي لطرقات قسنطينة الجبلية والمنحدرات أو للرحلات الطويلة للشرق والصحراء الجزائري."
  },
  {
    id: "car_5",
    brand: "رانج روفر",
    model: "فيلار - Range Rover Velar",
    year: 2024,
    category: "luxury",
    image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 35000,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 4.9,
    reviewsCount: 27,
    isAvailable: true,
    fuel: "diesel",
    seats: 5,
    deposit: 100000,
    description: "قمة الفخامة البريطانية على شوارع العاصمة. متوفرة مع سائق أو بدونه (بعد التحقق من الملف الشخصي). نظام تعليق هوائي مريح ونظام صوتي ثلاثي الأبعاد."
  },
  {
    id: "car_6",
    brand: "رونو",
    model: "سيمبول - Renault Symbol MIB",
    year: 2022,
    category: "economy",
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 4800,
    transmission: "manual",
    city: "عنابة",
    agencyId: "agency_annaba_milano",
    agencyName: "ميلانو رنت كار - عنابة",
    rating: 4.5,
    reviewsCount: 51,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 12000,
    description: "السيارة المفضلة للعائلات في عنابة بمرحلتها الصيفية والشتوية. خيار اقتصادي ومريح للغاية، صندوق خلفي كبير جداً يحمل كل الأغراض والسلات الصيفية للشواطئ."
  },
  {
    id: "car_7",
    brand: "هيونداي",
    model: "تكسون - Hyundai Tucson Sport",
    year: 2023,
    category: "suv",
    image: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 13500,
    transmission: "automatic",
    city: "بجاية",
    hostId: "host_11",
    hostName: "أمين بجاوي (مالك خاص)",
    rating: 4.6,
    reviewsCount: 15,
    isAvailable: true,
    fuel: "diesel",
    seats: 5,
    deposit: 30000,
    description: "هيونداي تكسون بتصميم هجومي فسيح وسقف بانوراما. مثالية للعائلات التي ترغب بزيارة جبال يما قورايا وشواطئ بجاية الخلابة براحة وأمان تامين."
  },
  {
    id: "car_wedding_mercedes",
    brand: "مرسيدس بنز",
    model: "S-Class S500 Royal Wedding",
    year: 2025,
    category: "wedding",
    image: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 38000,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 5.0,
    reviewsCount: 14,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 80000,
    description: "السيارة الملكية الأرقى بنقاء اللون الأبيض والشرائط المخصصة لمواكب الأعراس في الجزائر وحفلات الزفاف الفخمة. تسليم مع سائق محترف ببدلة رسمية."
  },
  {
    id: "car_wedding_royal",
    brand: "مازيراتي",
    model: "Maserati Ghibli Wedding Edition",
    year: 2024,
    category: "wedding",
    image: "https://images.unsplash.com/photo-1617469767053-d3b533dbb04e?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 42000,
    transmission: "automatic",
    city: "وهران",
    agencyId: "agency_oran_bahja",
    agencyName: "البهجة للسيارات الفاخرة",
    rating: 4.9,
    reviewsCount: 9,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 100000,
    description: "أناقة إيطالية رياضية خاطفة للأنظار للعروسين في ولاية وهران. مجهزة ومزينة بشريط وتور مخصص لزفاف ملكي لا يُنسى."
  },
  {
    id: "car_van_vclass",
    brand: "مرسيدس بنز",
    model: "V-Class Luxury VIP Van",
    year: 2025,
    category: "van",
    image: "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 26000,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 5.0,
    reviewsCount: 22,
    isAvailable: true,
    fuel: "diesel",
    seats: 8,
    deposit: 60000,
    description: "فان ميرسيدس في كلاس لكبار الشخصيات ورجال الأعمال والعائلات الكبيرة الراغبة بتنقل مريح للغاية بالجزائر العاصمة. مقاعد جلدية وخدمة VIP."
  },
  {
    id: "car_van_h1",
    brand: "هيونداي",
    model: "Hyundai H1 H-350 Elite",
    year: 2024,
    category: "van",
    image: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 16000,
    transmission: "manual",
    city: "قسنطينة",
    agencyId: "agency_const_bridges",
    agencyName: "وكالة الجسور المعلقة للسيارات",
    rating: 4.8,
    reviewsCount: 33,
    isAvailable: true,
    fuel: "diesel",
    seats: 9,
    deposit: 30000,
    description: "الفان العائلي الأوسع والأقوى هيونداي إتش 1 بـ 9 مقاعد حقيقية. ممتاز للسفر الطويل والرحلات العائلية الممتعة بالجزائر والشرق."
  },
  {
    id: "car_elec_id4",
    brand: "فولكس فاجن",
    model: "Volkswagen ID.4 Crozz EV",
    year: 2025,
    category: "luxury",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 17500,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 4.9,
    reviewsCount: 16,
    isAvailable: true,
    fuel: "electric",
    seats: 5,
    deposit: 40000,
    description: "سيارة كهربائية 105% كروية وهادئة للغاية. مثالية للتنقل الذكي والنظيف بوسط الجزائر العاصمة وبدون انبعاثات وبأفضل كفاءة طاقة."
  },
  {
    id: "car_elec_byd",
    brand: "بي واي دي",
    model: "BYD Han EV Super",
    year: 2025,
    category: "luxury",
    image: "https://images.unsplash.com/photo-161778813017-80ad40651399?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 21000,
    transmission: "automatic",
    city: "وهران",
    agencyId: "agency_oran_bahja",
    agencyName: "البهجة للسيارات الفاخرة",
    rating: 5.0,
    reviewsCount: 11,
    isAvailable: true,
    fuel: "electric",
    seats: 5,
    deposit: 50000,
    description: "الأناقة وقوة التسارع الخارق في أفخم سيارات السيدان الكهربائية للعلامة الرائدة BYD. تمتع بسياقة رافعة وصامتة بوهران."
  },
  {
    id: "car_lux_porsche",
    brand: "بورش",
    model: "Porsche Panamera Turbo S",
    year: 2026,
    category: "luxury",
    image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 46000,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 5.0,
    reviewsCount: 19,
    isAvailable: true,
    fuel: "essence",
    seats: 4,
    deposit: 120000,
    description: "بورش باناميرا تيربو إس الفائقة. سيارة رياضية خارقة رباعية الأبواب تجمع بين روح السباق الأسطورية لبورش وفخامة صالونات النخبة بالعاصمة."
  },
  {
    id: "car_wedding_rolls",
    brand: "رولز رويس",
    model: "Rolls-Royce Ghost Imperial",
    year: 2026,
    category: "wedding",
    image: "https://images.unsplash.com/photo-1632245889029-e406faaa34cd?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 75000,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 5.0,
    reviewsCount: 8,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 200000,
    description: "السيارة الحلم الأسمى لمواكب زفاف لا تُنسى. رولز رويس باللون الأبيض الملكي الفخم ومقصورة تزينها النجوم المضيئة. تُكرى خصيصاً مع سائق وباقات تزيين كاملة."
  },
  {
    id: "car_wedding_audi",
    brand: "أودي",
    model: "Audi A7 Sportback S-Line",
    year: 2025,
    category: "wedding",
    image: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 24000,
    transmission: "automatic",
    city: "وهران",
    agencyId: "agency_oran_bahja",
    agencyName: "البهجة للسيارات الفاخرة",
    rating: 4.9,
    reviewsCount: 15,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 60000,
    description: "أودي A7 بتشطيب S-Line الرياضي الأنيق باللون الأبيض اللؤلؤي المناسب جداً لزفة العروسين بأسلوب عصري وديناميكي راقٍ للغاية في الغرب الجزائري."
  },
  {
    id: "car_suv_gwagon",
    brand: "مرسيدس بنز",
    model: "G-Class G63 AMG Edition",
    year: 2026,
    category: "suv",
    image: "https://images.unsplash.com/photo-1520050206274-a1ae446cb3cc?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 48000,
    transmission: "automatic",
    city: "باتنة",
    agencyId: "agency_const_bridges",
    agencyName: "وكالة الجسور المعلقة للسيارات",
    rating: 5.0,
    reviewsCount: 22,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 150000,
    description: "وحش الطرق الوعرة والمدينة بلا منازع Mercedes G63 AMG. حضور وهيبة استثنائية، نظام دفع رباعي كامل، وصوت رياضي زائر يملأ الطريق فخامة وقوة."
  },
  {
    id: "car_suv_wrangler",
    brand: "جيب",
    model: "Jeep Wrangler Rubicon 4X4",
    year: 2025,
    category: "suv",
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 22000,
    transmission: "automatic",
    city: "قسنطينة",
    agencyId: "agency_const_bridges",
    agencyName: "وكالة الجسور المعلقة للسيارات",
    rating: 4.9,
    reviewsCount: 16,
    isAvailable: true,
    fuel: "essence",
    seats: 5,
    deposit: 50000,
    description: "جيب رانجلر روبيكون المخصصة للمغامرات الجبلية والبرية الصعبة بالتصميم الأيقوني المكشوف ونظام الدفع 4x4 الثقيل لتجربة كراء مثيرة وحرية تامة."
  },
  {
    id: "car_van_camper_vw",
    brand: "فولكس فاجن",
    model: "VW California Overland Camper",
    year: 2025,
    category: "van",
    image: "https://images.unsplash.com/photo-1527685216219-c7fe7b7ed1ab?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 19500,
    transmission: "manual",
    city: "بجاية",
    hostName: "جمال القبائلي (مستضيف للتخييم)",
    rating: 5.0,
    reviewsCount: 14,
    isAvailable: true,
    fuel: "diesel",
    seats: 4,
    deposit: 50000,
    description: "فان تخييم فولكس فاجن كاليفورنيا الأسطوري للمغامرين ومحبي الهواء الطلق بجانب شواطئ بجاية وجبالها. مجهز بسرير مزدوج علوي منبثق، مطبخ صغير وثلاجة."
  },
  {
    id: "car_van_camper_sprinter",
    brand: "مرسيدس بنز",
    model: "Sprinter Offgrid Adventure Coach",
    year: 2026,
    category: "van",
    image: "https://images.unsplash.com/photo-1513313778780-9ae4807465f0?auto=format&fit=crop&q=80&w=600",
    pricePerDay: 32000,
    transmission: "automatic",
    city: "الجزائر العاصمة",
    agencyId: "agency_alger_ym",
    agencyName: "وكالة اليمامة لكراء السيارات",
    rating: 4.9,
    reviewsCount: 7,
    isAvailable: true,
    fuel: "diesel",
    seats: 2,
    deposit: 80000,
    description: "منزل متنقل حقيقي فاخر لرحلة استثنائية Off-grid. سبرينتر كامپر مع طاقة شمسية كاملة، مكيف هواء، مرحاض ومغسلة داخليين ومساحة لإعداد القهوة والوجبات."
  }
];

export const INITIAL_USER: User = {
  id: "guest",
  name: "زائر",
  email: "",
  avatar: "",
  walletBalance: 0,
  isDriverVerified: false,
  isHost: false,
  hasPendingVerification: false,
  registrationDate: "",
  isGuest: true
};

export const PRESET_USER: User = {
  id: "user_algeria_1",
  name: "بلال غواط",
  email: "bilalghouat5@gmail.com",
  avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
  walletBalance: 24500, // in DZD
  isDriverVerified: true,
  licenseNumber: "DZ-2019-3549281",
  identityCardNumber: "CNI-1029384759",
  isHost: true,
  hasPendingVerification: false,
  registrationDate: "2024-01-15",
  phone: "+213 555 125 152",
  isGuest: false
};

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev_1",
    userName: "عبد الصمد بن صالح",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100",
    rating: 5,
    comment: "السيارة كانت في حالة ممتازة، والتعامل مع الوكالة سريع ومحترف جداً. استلمت السيارة نظيفة ومعها خزان وقود ممتلئ.",
    date: "2026-05-12",
    carId: "car_1"
  },
  {
    id: "rev_2",
    userName: "مريم بوزيد",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=100",
    rating: 5,
    comment: "تجربة رائعة في العرس! الجولف 8 كانت نظيفة لدرجة مدهشة وكل ميزاتها تعمل بسلاسة. أنصح بالتعامل معهم بشدة.",
    date: "2026-05-24",
    carId: "car_2"
  },
  {
    id: "rev_3",
    userName: "سفيان وهراني",
    userAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=100",
    rating: 4,
    comment: "السيارة مناسبة جداً والسعر ممتاز في متناول الجميع، الاستلام والتسليم تم في الموعد تماماً.",
    date: "2026-06-02",
    carId: "car_6"
  }
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  {
    id: "not_1",
    title: "تم توثيق رخصتك بنجاح ✅",
    content: "تهانينا! تمت مراجعة رخصة القيادة والبطاقة الوطنية الخاصة بك. يمكنك الآن حجز أي سيارة على التطبيق بشكل فوري.",
    type: "system",
    date: "قبل يومين",
    read: false
  },
  {
    id: "not_2",
    title: "هدية ترحيبية في محفظتك 🎁",
    content: "تمت إضافة مبلغ قدره 2,000 دج مجاناً بمناسبة أول تسجيل لك في تورو الجزائر. استمتع برحلتك القادمة!",
    type: "wallet",
    date: "قبل 4 أيام",
    read: true
  },
  {
    id: "not_3",
    title: "سيارتك الهيونداي تكسون جاهزة للإيجار 🚗",
    content: "لقد قمت بإضافة سيارتك بنجاح في لوحة تحكم المالكين. ستظهر الآن في نتائج البحث للباحثين عن سيارات في بجاية.",
    type: "host",
    date: "قبل 5 أيام",
    read: true
  }
];
