import React, { createContext, useContext, useState, useEffect } from "react";

export type LanguageType = "ar" | "en" | "fr" | "amazigh";

interface LanguageContextProps {
  language: LanguageType;
  setLanguage: (lang: LanguageType) => void;
  t: (text: string) => string;
  isRtl: boolean;
  dir: "rtl" | "ltr";
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

const dictionary: Record<LanguageType, Record<string, string>> = {
  ar: {}, // Arabic is the default source language, so it returns the input text itself
  en: {
    // Nav & Tabs
    "البحث": "Search",
    "المفضلة": "Favorites",
    "رحلاتي": "My Trips",
    "الرسائل": "Messages",
    "المزيد": "More",
    "الرحلات": "Trips",
    "السيارات": "Cars",
    "الأعمال": "Business",
    "مرحباً بك": "Welcome",
    "مرحباً بك في درايف RENT!": "Welcome to Drive RENT!",
    "تسجيل الدخول أو التسجيل": "Log In or Sign Up",
    "عرض وتعديل الملف الشخصي": "View & Edit Profile",
    "كن مستضيفاً": "Become a Host",
    "كن مضيفاً": "Become a Host",
    "الحساب": "Account",
    "التحويل إلى وضع المضيف (Host Mode)": "Switch to Host Mode",
    "التحويل إلى وضع المستأجر (Guest Mode)": "Switch to Guest Mode",
    "التحويل لوضع المستأجر": "Switch to Guest Mode",
    "التحويل إلى وضع المستأجر": "Switch to Guest Mode",
    "اسأل درايف RENT": "Ask Drive RENT",
    "مساعد درايف RENT الذكي 🤖": "Drive RENT Smart Assistant 🤖",
    "مساعد درايف RENT الذكي بالجزائر 🤖": "Drive RENT Smart Assistant in Algeria 🤖",
    "بطاقات الهدايا (درايف RENT Gift)": "Gift Cards (Drive RENT Gift)",
    "بطاقات الهدايا": "Gift Cards",
    "لماذا تختار درايف RENT": "Why Choose Drive RENT",
    "لماذا تختار درايف RENT؟": "Why Choose Drive RENT?",
    "كيف تصبح مستضيفاً على درايف RENT؟": "How to Become a Host on Drive RENT?",
    "الحصول على المساعدة": "Get Help",
    "الشؤون القانونية": "Legal Policies",
    "تسجيل الخروج": "Log Out",
    "تغيير لغة التطبيق": "App Language",
    "اختر لغة التطبيق": "Select Language",
    "حفظ": "Save",
    "تم حفظ الإعدادات بنجاح": "Settings saved successfully",
    "العربية": "Arabic",
    "الأمازيغية": "Amazigh (Tamazight)",
    "لغة التطبيق": "App Language",
    "الإنجليزية": "English",
    "الفرنسية": "French",
    
    // Explore Tab / Filtering
    "ابحث عن سيارات في الجزائر...": "Search for cars in Algeria...",
    "تصفية": "Filters",
    "كل الفئات": "All Categories",
    "اقتصادي": "Economy",
    "عائلي": "Family",
    "فاخر": "Luxury",
    "رياضية": "Sport",
    "سعر اليوم": "Daily Price",
    "حجز فوري": "Instant Book",
    "سيارات مخصصة للزفاف": "Wedding Cars",
    "سيارات مميزة من شركائنا الموثوقين": "Premium cars from our trusted partners",
    "مستضيف متميز": "Superhost",
    "تأمين حماية شامل بالتعاقد مع درايف RENT للتكافل": "Full insurance protection with Drive RENT Takaful",
    "تأمين درايف RENT والوساطة (5%):": "Drive RENT insurance & fees (5%):",
    "مستضيف متميز درايف RENT": "Superhost Drive RENT",
    "مضيف متميز درايف RENT": "Superhost Drive RENT",
    "مضيف متميز • درايف RENT Partner": "Superhost • Drive RENT Partner",
    "حجز فوري مؤكد": "Confirmed Instant Booking",
    "ناقل حركة أوتوماتيكي": "Automatic Box",
    "أوتوماتيك": "Automatic",
    "يدوي": "Manual",
    "الوقود": "Fuel",
    "المحرك": "Engine",
    "بنزين": "Petrol",
    "ديزل": "Diesel",
    "هجين": "Hybrid",
    "كهربائية": "Electric",
    "دج/يوم": "DZD/Day",
    "دج": "DZD",
    "طلب الحجز": "Request Booking",
    "تأكيد الحجز": "Confirm Booking",
    "تأكيد": "Confirm",
    "إلغاء": "Cancel",
    "تفاصيل السيارة": "Car Details",
    "الميزات والمواصفات": "Specs & Features",
    "تقييم المضيف": "Host Rating",
    "التقييمات": "Reviews",
    "الموقع والاتصال": "Location & Contact",
    "تحديد تاريخ الكراء": "Select Rental Period",
    "تاريخ البدء": "Start Date",
    "تاريخ الانتهاء": "End Date",
    "السعر الإجمالي": "Total Price",
    "الوديعة / الكفالة": "Security Deposit",
    "موقع مكتب الاستعلام": "Inquiry Office Location",
    "السيارة متوفرة للكراء": "Available for rent",
    "السيارة غير متوفرة حالياً": "Currently unavailable",
    "تأكيد الكراء": "Confirm Rental",
    "أيام الكراء الإجمالية:": "Total rental days:",
    "سعر كراء السيارة الكلي:": "Total car rental price:",
    "تأمين درايف RENT وعمولة الخدمة:": "Drive RENT insurance & fees:",
    "المبلغ الكلي المستحق:": "Total amount due:",
    "الوديعة الضمانية المستردة (تدفع عند الاستلام للوكالة):": "Refundable security deposit (paid directly to agency):",
    "مبلغ الوديعة مسترد كلياً فور انتهاء فترة الكراء وثبوت سلامة السيارة.": "Deposit is fully refundable after vehicle check.",
    "الاستمرار وتأكيد الحجز الفوري": "Proceed & Confirm Instant Booking",
    "سيارات": "cars",
    "تبدأ من": "starts from",
    "يوم": "day",
    "التصنيف الفئوي": "Class Category",
    "ناقل السرعات": "Gearbox",
    "عرض الكل": "Show All",
    "عنا": "About us",
    "حياك الله": "Welcome",
    "تقييم": "rating",
    "مشاهدة كافة التعليقات والتقييمات": "View all ratings and reviews",
    "التقييمات والتعليقات": "Ratings and reviews",
    "بناءً على": "Based on",
    "آراء المستأجرين الأخيرة": "Recent guest reviews",
    "جاري تحميل المزيد من التقييمات...": "Loading more reviews...",
    "تم تحميل كافة التعليقات والتقييمات الموثقة": "All verified reviews loaded",
    "اسحب للأعلى لمشاهدة المزيد": "Swipe up to load more",
    "Cleanliness": "Cleanliness",
    "Maintenance": "Maintenance",
    "Communication": "Communication",
    "Convenience": "Convenience",
    "Accuracy": "Accuracy",

    // Bookings / Trips Tab
    "حجوزاتي": "My Reservations",
    "رحلة قادمة": "Upcoming Trip",
    "رحلة سابقة": "Past Trip",
    "حالات الحجز": "Booking Status",
    "قيد الانتظار": "Pending",
    "مؤكد": "Confirmed",
    "ملغي": "Cancelled",
    "نشط": "Active",
    "مكتمل": "Completed",
    "كود الحجز:": "Booking Code:",
    "استعراض العقد": "View Contract",
    "تقييم التجربة": "Rate Trip",
    "تواصل مع المضيف": "Contact Host",
    "تواصل هاتفي": "Call Host",
    "اتصال": "Call",
    "اكتشف آلاف السيارات المتاحة على درايف RENT واحجز رحلتك القادمة.": "Discover thousands of cars on Drive RENT and book your next ride.",
    "اكتشف آلاف السيارات المتاحة على <span className=\"font-extrabold text-zinc-300\">درايف RENT</span> واحجز رحلتك القادمة.": "Discover thousands of cars on Drive RENT and book your next ride.",
    "ملاحظة: هذا اتصال افتراضي ومحاكاة مدمجة داخل تطبيق درايف RENT الجزائر لسهولة تواصل الأعضاء مع الوكالات المعتمدة.": "Note: This is a simulated call integrated inside Drive RENT Algeria for testing.",
    "تم إلغاء الحجز وسحب الطلب": "Trip cancelled and request withdrawn",
    "نشطة الآن": "Active Now",
    "قيد معالجة الطلب": "Pending processing",
    "انتهى الكراء": "Rental finished",
    "كراء مؤكد": "Rental confirmed",
    "تاريخ كراء السيارة:": "Rental period:",
    "سعر الكراء الكلي:": "Total cost:",
    "رمز تأكيد الحجز المباشر:": "Confirmation code:",
    "تفاصيل عقد كراء مركبة مؤمنة بالمنصة": "Details of the secured rental contract",

    // Profile & Account Settings
    "بيانات الحساب": "Account Info",
    "اسم المضيف / الوكالة بالمنصة": "Host / Agency Name",
    "بريدك الإلكتروني (لتوثيق التعامل الفوري)": "Your Email (Strict Verification)",
    "الهاتف للاتصال من المكتتبين": "Phone for Rental Contacts",
    "نبذة تعريفية وموقع مكتب الاستعلام": "About & Inquiry Office Address",
    "تم حفظ وتزامن ملف حسابك بشكل فوري آمن بالمنصة.": "Your account profile has been saved and synced securely on the platform.",
    "تم حفظ وتزامن ملف حسابك بشكل فوري آمن.": "Your account profile has been saved and synced securely.",
    "أرشيف المعاملات الأخيرة": "Recent Transactions",
    "تنزيل الفاتورة": "Download Invoice",
    "شحن المحفظة": "Top Up Wallet",
    "رصيد المحفظة الكلي": "Total Wallet Balance",
    "رصيدك الكلي بالمحفظة:": "Total balance in wallet:",
    "إيداع فوري آمن": "Instant Secure Deposit",
    "البطاقة الذهبية أو بطاقة CIB": "Edahabia or CIB Card",
    "توثيق الحساب": "Identity Verification",
    "بطاقة التعريف الوطنية": "National Identity Card ID",
    "رخصة السياقة": "Driver's License",
    "يرجى توفير ورفع الوثائق المنصوص عليها لتعزيز ثقة المكتتبين وتفعيل الفاتورة التأمينية المعتمدة لواردات كراء السيارات.": "Please provide and upload the required documents to increase trust and activate the certified insurance invoice.",
    "السجل التجاري الجزائري (RC)": "Algerian Commercial Registry (RC)",
    "بطاقة التعريف الجبائي (NIF)": "Tax Identification Card (NIF)",
    "دفتر شروط تأمين المركبة الكلي": "Comprehensive Vehicle Insurance booklet",
    "تم رفع ملف الورقة الثبوتية بنجاح! يتم التدقيق والتحقق منها وتنشيط حسابك الآن.": "Identification document uploaded successfully! Verification in progress.",
    "الملف الشخصي للمضيف": "Host Profile",
    "مركز الأرباح المالي": "Financial Earnings Hub",
    "الملفات والوثائق القانونية": "Files & Legal Documents",
    "الإعدادات والخصوصية": "Settings & Privacy",
    "تنفيذ طلب الإيداع الفوري": "Confirm Instant Top Up",
    "أدخل قيمة الرصيد المراد إضافته (دج)": "Enter top up amount (DZD)",
    "بوابة الدفع الإلكتروني الجزائرية المقبولة": "Accepted Algerian Electronic Payment Gateways",
    "الرصيد الحالي بالمحفظة:": "Current Wallet Balance:",
    "تاريخ التسجيل بالجزائر:": "Registration Date in Algeria:",
    "معلومات الاتصال الموثقة": "Verified Contact Info",
    "تعديل الحساب": "Edit Profile",
    "التنبيهات والإشعارات": "Notifications Preferences",
    "تفضيلات ناقل الحركة المفضل": "Preferred Gear Transmission",
    "تنبيهات الرسائل والنظام الفورية (SMS)": "Instant Messages & System Alerts (SMS)",
    "تنبيهات إلكترونية ومستجدات المنصة": "Email Notifications",
    "العقود والمسؤوليات": "Contracts & Responsibilities",
    "بند العقود القانوني وكفالة السيارات": "Legal Contracts & Security Bond Clause",
    "شروط وقوانين المسؤولية المدنية": "Terms & Liability Regulations",
    "تلقي تنبيهات وعوائد الكراء الفورية": "Receive instant booking alerts & payouts",
    "مبارك! لقد تم تسجيل معلومات وكالتك": "Congratulations! Your rental agency has been registered",
    
    // Support Chat
    "الدعم الفني والإستعلام": "Support & Inquiries",
    "اكتب رسالتك وسيجيبك مرشدنا الآلي فوراً...": "Write your message, our bot will reply instantly...",

    // Host Dashboard / Business
    "الرصيد الكلي المقبوض": "Total Revenue Collected",
    "مستحقات هذا الأسبوع": "Earnings This Week",
    "مبالغ قيد التصفية": "Pending Payouts",
    "نشاطات أسطولك الحالية": "Your Fleet Active Trips",
    "مستأجر:": "Renter:",
    "إنشاء وكالتك الخاصة": "Register Your Car Agency",
    "سجل وكالتك وحقق عوائد مستمرة": "Register your agency and earn regular revenue",
    "خطوات لتصبح مضيفاً": "Steps to become a host",
  },
  fr: {
    // Nav & Tabs
    "البحث": "Recherche",
    "المفضلة": "Favoris",
    "رحلاتي": "Mes Voyages",
    "الرسائل": "Messages",
    "المزيد": "Plus",
    "الرحلات": "Voyages",
    "السيارات": "Voitures",
    "الأعمال": "Activités",
    "مرحباً بك": "Bienvenue",
    "مرحباً بك في درايف RENT!": "Bienvenue sur Drive RENT !",
    "تسجيل الدخول أو التسجيل": "Connexion ou Inscription",
    "عرض وتعديل الملف الشخصي": "Voir & Modifier Profil",
    "كن مستضيفاً": "Devenir Hôte",
    "كن مضيفاً": "Devenir Hôte",
    "الحساب": "Compte",
    "التحويل إلى وضع المضيف (Host Mode)": "Passer en Mode Hôte",
    "التحويل إلى وضع المستأجر (Guest Mode)": "Passer en Mode Locataire",
    "التحويل لوضع المستأجر": "Passer en Mode Locataire",
    "التحويل إلى وضع المستأجر": "Passer en Mode Locataire",
    "اسأل درايف RENT": "Demander à Drive RENT",
    "مساعد درايف RENT الذكي 🤖": "Assistant Intelligent Drive RENT 🤖",
    "مساعد درايف RENT الذكي بالجزائر 🤖": "Assistant Intelligent Drive RENT en Algérie 🤖",
    "بطاقات الهدايا (درايف RENT Gift)": "Cartes Cadeaux",
    "بطاقات الهدايا": "Cartes Cadeaux",
    "لماذا تختار درايف RENT": "Pourquoi Drive RENT ?",
    "لماذا تختار درايف RENT؟": "Pourquoi Drive RENT ?",
    "كيف تصبح مستضيفاً على درايف RENT؟": "Comment devenir hôte sur Drive RENT ?",
    "الحصول على المساعدة": "Assistance",
    "الشؤون القانونية": "Mentions Légales",
    "تسجيل الخروج": "Déconnexion",
    "تغيير لغة التطبيق": "Langue de l'app",
    "اختر لغة التطبيق": "Choisir la Langue",
    "حفظ": "Sauvegarder",
    "تم حفظ الإعدادات بنجاح": "Paramètres enregistrés avec succès",
    "العربية": "Arabe",
    "الأمازيغية": "Amazighe",
    "لغة التطبيق": "Langue de l'app",
    "الإنجليزية": "Anglais",
    "الفرنسية": "Français",

    // Explore Tab / Filtering
    "ابحث عن سيارات في الجزائر...": "Rechercher des voitures en Algérie...",
    "تصفية": "Filtres",
    "كل الفئات": "Catégories",
    "اقتصادي": "Économique",
    "عائلي": "Familiale",
    "فاخر": "De Luxe",
    "رياضية": "Sport",
    "سعر اليوم": "Prix journalier",
    "حجز فوري": "Résat Instantanée",
    "سيارات مخصصة للزفاف": "Voitures de mariage",
    "سيارات مميزة من شركائنا الموثوقين": "Voitures premium sélectionnées",
    "مستضيف متميز": "Superhôte",
    "تأمين حماية شامل بالتعاقد مع درايف RENT للتكافل": "Protection tous risques avec Drive RENT Takaful",
    "تأمين درايف RENT والوساطة (5%):": "Assurance Drive RENT & frais (5%) :",
    "مستضيف متميز درايف RENT": "Superhôte Drive RENT",
    "مضيق متميز درايف RENT": "Superhôte Drive RENT",
    "مضيف متميز درايف RENT": "Superhôte Drive RENT",
    "مضيف متميز • درايف RENT Partner": "Superhôte • Partenaire Drive RENT",
    "حجز فوري مؤكد": "Réservation instantanée confirmée",
    "ناقل حركة أوتوماتيكي": "Boîte Auto",
    "أوتوماتيك": "Automatique",
    "يدوي": "Manuelle",
    "الوقود": "Carburant",
    "المحرك": "Moteur",
    "بنزين": "Essence",
    "ديزل": "Diesel",
    "هجين": "Hybride",
    "كهربائية": "Électrique",
    "دج/يوم": "DA/Jour",
    "دج": "DZD",
    "طلب الحجز": "Demander Réservation",
    "تأكيد الحجز": "Confirmer Réservation",
    "تأكيد": "Confirmer",
    "إلغاء": "Annuler",
    "تفاصيل السيارة": "Caractéristiques",
    "الميزات والمواصفات": "Spécifications & Équipements",
    "تقييم المضيف": "Note de l'hôte",
    "التقييمات": "Commentaires",
    "الموقع والاتصال": "Localisation & Contacts",
    "تحديد تاريخ الكراء": "Dates de location",
    "تاريخ البدء": "Date début",
    "تاريخ الانتهاء": "Date fin",
    "السعر الإجمالي": "Prix total",
    "الوديعة / الكفالة": "Caution de garantie",
    "موقع مكتب الاستعلام": "Bureau de renseignement",
    "السيارة متوفرة للكراء": "Disponible à la location",
    "السيارة غير متوفرة حالياً": "Non disponible pour le moment",
    "تأكيد الكراء": "Confirmer la location",
    "أيام الكراء الإجمالية:": "Nombre de jours :",
    "سعر كراء السيارة الكلي:": "Tarif de location total :",
    "تأمين درايف RENT وعمولة الخدمة:": "Assurance Drive RENT & service :",
    "المبلغ الكلي المستحق:": "Montant total dû :",
    "الوديعة الضمانية المستردة (تدفع عند الاستلام للوكالة):": "Caution remboursable (à payer à la livraison) :",
    "مبلغ الوديعة مسترد كلياً فور انتهاء فترة الكراء وثبوت سلامة السيارة.": "La caution est entièrement remboursée après restitution conforme.",
    "الاستمرار وتأكيد الحجز الفوري": "Continuer & Confirmer",
    "سيارات": "voitures",
    "تبدأ من": "à partir de",
    "يوم": "jour",
    "التصنيف الفئوي": "Catégories",
    "ناقل السرعات": "Vitesse",
    "عرض الكل": "Voir Tout",
    "عنا": "À propos",
    "حياك الله": "Bienvenue",
    "تقييم": "Note",
    "مشاهدة كافة التعليقات والتقييمات": "Voir toutes les évaluations et avis",
    "التقييمات والتعليقات": "Évaluations et avis",
    "بناءً على": "Basé sur",
    "آراء المستأجرين الأخيرة": "Avis récents des voyageurs",
    "جاري تحميل المزيد من التقييمات...": "Chargement d'autres avis...",
    "تم تحميل كافة التعليقات والتقييمات الموثقة": "Tous les avis vérifiés ont été chargés",
    "اسحب للأعلى لمشاهدة المزيد": "Faire défiler vers le haut pour plus d'avis",
    "Cleanliness": "Propreté",
    "Maintenance": "Entretien / Maintenance",
    "Communication": "Communication",
    "Convenience": "Confort / Praticité",
    "Accuracy": "Précision",

    // Bookings / Trips
    "حجوزاتي": "Mes Voyages",
    "رحلة قادمة": "Prochain Voyage",
    "رحلة سابقة": "Voyage Passé",
    "حالات الحجز": "Statut de réservation",
    "قيد الانتظار": "En attente",
    "مؤكد": "Confirmé",
    "ملغي": "Annulé",
    "نشط": "Actif",
    "مكتمل": "Terminé",
    "كود الحجز:": "Code de réservation :",
    "استعراض العقد": "Consulter le contrat",
    "تقييم التجربة": "Laisser un avis",
    "تواصل مع المضيف": "Contacter l'hôte",
    "تواصل هاتفي": "Appeler l'hôte",
    "اتصال": "Appeler",
    "اكتشف آلاف السيارات المتاحة على درايف RENT واحجز رحلتك القادمة.": "Découvrez des milliers de voitures sur Drive RENT et planifiez votre voyage.",
    "اكتشف آلاف السيارات المتاحة على <span className=\"font-extrabold text-zinc-300\">درايف RENT</span> واحجز رحلتك القادمة.": "Découvrez des milliers de voitures sur Drive RENT et planifiez votre voyage.",
    "ملاحظة: هذا اتصال افتراضي ومحاكاة مدمجة داخل تطبيق درايف RENT الجزائر لسهولة تواصل الأعضاء مع الوكالات المعتمدة.": "Note : Cet appel est virtuel. Il s'agit d'une simulation.",
    "تم إلغاء الحجز وسحب الطلب": "Réservation annulée avec succès",
    "نشطة الآن": "Actif en cours",
    "قيد معالجة الطلب": "Demande en cours de traitement",
    "انتهى الكراء": "Location terminée",
    "كراء مؤكد": "Location confirmée",
    "تاريخ كراء السيارة:": "Période de location :",
    "سعر الكراء الكلي:": "Coût total de location :",
    "رمز تأكيد الحجز المباشر:": "Code de confirmation :",
    "تفاصيل عقد كراء مركبة مؤمنة بالمنصة": "Détails du contrat de location sécurisé",

    // Profile & Account Settings
    "بيانات الحساب": "Informations Compte",
    "اسم المضيف / الوكالة بالمنصة": "Nom de l'hôte / de l'agence",
    "بريدك الإلكتروني (لتوثيق التعامل الفوري)": "Adresse e-mail (Pour validation)",
    "الهاتف للاتصال من المكتتبين": "Téléphone pour contact client",
    "نبذة تعريفية وموقع مكتب الاستعلام": "Description & Adresse du bureau",
    "تم حفظ وتزامن ملف حسابك بشكل فوري آمن بالمنصة.": "Votre profil a été sauvegardé et mis à jour avec succès.",
    "تم حفظ وتزامن ملف حسابك بشكل فوري آمن.": "Votre profil a été sauvegardé et mis à jour avec succès.",
    "أرشيف المعاملات الأخيرة": "Transactions Récentes",
    "تنزيل الفاتورة": "Facture PDF",
    "شحن المحفظة": "Recharger mon compte",
    "رصيد المحفظة الكلي": "Solde de mon portefeuille",
    "رصيدك الكلي بالمحفظة:": "Solde actuel :",
    "إيداع فوري آمن": "Rechargement Sécurisé",
    "البطاقة الذهبية أو بطاقة CIB": "Carte Edahabia ou CIB",
    "توثيق الحساب": "Vérification d'Identité",
    "بطاقة التعريف الوطنية": "Carte d'Identité Nationale (CNI)",
    "رخصة السياقة": "Permis de conduire",
    "يرجى توفير ورفع الوثائق المنصوص عليها لتعزيز ثقة المكتتبين وتفعيل الفاتورة التأمينية المعتمدة لواردات كراء السيارات.": "Veuillez téléverser les justificatifs requis pour authentifier votre agence.",
    "السجل التجاري الجزائري (RC)": "Registre du Commerce (RC)",
    "بطاقة التعريف الجبائي (NIF)": "Numéro d'Identification Fiscale (NIF)",
    "دفتر شروط تأمين المركبة الكلي": "Contrat d'assurance multirisque auto",
    "تم رفع ملف الورقة الثبوتية بنجاح! يتم التدقيق والتحقق منها وتنشيط حسابك الآن.": "Document téléversé ! En cours de vérification.",
    "الملف الشخصي للمضيف": "Profil Hôte",
    "مركز الأرباح المالي": "Gains & Recettes",
    "الملفات والوثائق القانونية": "Documents de conformité rattachés",
    "الإعدادات والخصوصية": "Paramètres & Sécurité",
    "تنفيذ طلب الإيداع الفوري": "Soumettre le rechargement",
    "أدخل قيمة الرصيد المراد إضافته (دج)": "Entrez le montant à créditer (DZD)",
    "بوابة الدفع الإلكتروني الجزائرية المقبولة": "Passerelles de paiement algériennes acceptées",
    "الرصيد الحالي بالمحفظة:": "Solde actuel dans le portefeuille :",
    "تاريخ التسجيل بالجزائر:": "Date d'inscription officielle :",
    "معلومات الاتصال الموثقة": "Coordonnées vérifiées",
    "تعديل الحساب": "Éditer le profil",
    "التنبيهات والإشعارات": "Préférences de notification",
    "تفضيلات ناقل الحركة المفضل": "Préférence de boîte de vitesses",
    "تنبيهات الرسائل والنظام الفورية (SMS)": "Alertes SMS instantanées",
    "تنبيهات إلكترونية ومستجدات المنصة": "Lettre d'information par e-mail",
    "العقود والمسؤوليات": "Contrats de location & Responsabilités",
    "بند العقود القانوني وكفالة السيارات": "Clause d'assurance contractuelle",
    "شروط وقوانين المسؤولية المدنية": "Réglementations de la responsabilité civile",
    "تلقي تنبيهات وعوائد الكراء الفورية": "Alertes de réservations immédiates",
    "مبارك! لقد تم تسجيل معلومات وكالتك": "Félicitations ! Votre agence est enregistrée",

    // Support Chat
    "الدعم الفني والإستعلام": "Support technique & Info",
    "اكتب رسالتك وسيجيبك مرشدنا الآلي فوراً...": "Saisissez votre message, notre bot répondra instantanément...",

    // Host Dashboard / Business
    "الرصيد الكلي المقبوض": "Total des revenus collectés",
    "مستحقات هذا الأسبوع": "Revenus cette semaine",
    "مبالغ قيد التصفية": "Paiements en attente",
    "نشاطات أسطولك الحالية": "Voyages en cours de votre flotte",
    "مستأجر:": "Locataire :",
    "إنشاء وكالتك الخاصة": "Inscrire Votre Agence de Location",
    "سجل وكالتك وحقق عوائد مستمرة": "Enregistrez votre agence pour générer des gains réguliers",
    "خطوات لتصبح مضيفاً": "Étapes pour devenir hôte",
  },
  amazigh: {
    // Nav & Tabs
    "البحث": "Anadi (ⵔⵣⵓ)",
    "المفضلة": "Ikhf can (ⵜⵉⴼⵔⵉⵜ)",
    "رحلاتي": "Inigouts-inu (ⵉⵎⵓⴷⴷⵓⵜⵏ)",
    "الرسائل": "Tibratin (ⵜⵉⴱⵔⴰⵜⵉⵏ)",
    "المزيد": "Uggar (ⵓⴳⴳⴰⵔ)",
    "الرحلات": "Inigouts (ⵉⵎⵓⴷⴷⵓⵜⵏ)",
    "السيارات": "Tikarratin (ⵜⵉⴽⴰⵔⵔⴰⵜⵉⵏ)",
    "الأعمال": "Imahilen (ⵉⵎⴰⵀⵉⵍⵏ)",
    "مرحباً بك": "Ansuf (ⴰⵏⵙⵓⴼ)",
    "مرحباً بك في درايف RENT!": "Ansuf ɣer Drive RENT! (ⴰⵏⵙⵓⴼ ⴳ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "تسجيل الدخول أو التسجيل": "Kcem neɣ tgezda (ⴽⵛⵎ / ⵜⴳⴻⵣⴷⴰ)",
    "عرض وتعديل الملف الشخصي": "Udm n user (ⵓⴷⵎ ⵏ ⵓⵙⴻⵔ)",
    "كن مستضيفاً": "G udbab (ⴳ ⵓⴷⴱⴰⴱ)",
    "كن مضيفاً": "G udbab (ⴳ ⵓⴷⴱⴰⴱ)",
    "الحساب": "Amiḍan (ⴰⵎⵉⴹⴰⵏ)",
    "التحويل إلى وضع المضيف (Host Mode)": "Sbed d udbab (ⵙⴱⴻⴷ ⴷ ⵓⴷⴱⴰⴱ)",
    "التحويل إلى وضع المستأجر (Guest Mode)": "Sbed d amsaf (ⵙⴱⴻⴷ ⴷ ⴰⵎsaf)",
    "التحويل لوضع المستأجر": "Sbed d amsaf (ⵙⴱⴻⴷ ⴷ ⴰⵎsaf)",
    "التحويل إلى وضع المستأجر": "Sbed d amsaf (ⵙⴱⴻⴷ ⴷ ⴰⵎsaf)",
    "اسأل درايف RENT": "Seqsi Drive RENT (ⵙⴻⵇⵙⵉ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "مساعد درايف RENT الذكي 🤖": "Ammusu Drive RENT (ⴰⵎⵎⵓⵙⵓ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ 🤖)",
    "مساعد درايف RENT الذكي بالجزائر 🤖": "Ammusu Drive RENT (ⴰⵎⵎⵓⵙⵓ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ 🤖)",
    "بطاقات الهدايا (درايف RENT Gift)": "Tifliwin n Drive RENT (ⵜⵉⴼⵍⵉⵡⵉⵏ ⵏ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "بطاقات الهدايا": "Tifliwin n Drive RENT (ⵜⵉⴼⵍⵉⵡⵉⵏ)",
    "لماذا تختار درايف RENT": "Acuɣer Drive RENT (ⴰⵛⵓɣⴻⵔ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "لماذا تختار درايف RENT؟": "Acuɣer Drive RENT? (ⴰⵛⵓɣⴻⵔ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ ?)",
    "كيف تصبح مستضيفاً على درايف RENT؟": "Amek ara d-iliḍ d udbab (ⴰⵎⴻⴽ ⴳ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "الحصول على المساعدة": "Tallelt (ⵜⴰⵍⵍⴻⵍⵜ)",
    "الشؤون القانونية": "Azerf (ⴰⵣⴻⵔⴼ)",
    "تسجيل الخروج": "Anufeɣ (ⴰⵏⵓⴼⴻⵖ)",
    "تغيير لغة التطبيق": "Senfel tutlayt (ⵙⴻⵏⴼⴻⵍ ⵜⵓⵜⵍⴰⵢⵜ)",
    "اختر لغة التطبيق": "Fren tutlayt (ⴼⵔⴻⵏ ⵜⵓⵜⵍⴰⵢⵜ)",
    "حفظ": "Kles (ⴽⵍⴻⵙ)",
    "تم حفظ الإعدادات بنجاح": "Ayen yules (ⴰيجان ⵢⵓⵍⴻⵙ)",
    "العربية": "Taɛrabt (ⵜⴰⵄⵔⴰⴱⵜ)",
    "الأمازيغية": "Tamaziɣt (ⵜⴰⵎⴰⵣⵉⵖⵜ)",
    "لغة التطبيق": "Tutlayt n usnas (ⵜⵓⵜⵍⴰⵢⵜ)",
    "الإنجليزية": "Taglizit (ⵜⴰⴳⵍⵉⵣⵉⵜ)",
    "الفرنسية": "Tafrensist (ⵜⴰⴼⵔⴻⵏⵙⵉⵙⵜ)",

    // Explore Tab / Filtering
    "ابحث عن سيارات في الجزائر...": "Anadi af tikarratin di Lzayer... (ⵔⵣⵓ)",
    "تصفية": "Afran (ⴰⴼⵔⴰْن)",
    "كل الفئات": "Kkes tismilin (ⴽⴽⴻⵙ ⵜⵉⵙⵎⵉⵍⵉⵏ)",
    "اقتصادي": "Ufriz (ⵓⴼⵔⵉⵣ)",
    "عائلي": "Tawacult (ⵜⴰⵡⴰⵛⵓⵍⵜ)",
    "فاخر": "Anesbaɣur (ⴰⵏⴻⵙⴱⴰⵖⵓⵔ)",
    "رياضية": "Tunna (ⵜⵓⵏⵏⴰ)",
    "سعر اليوم": "Atig n wass (ⴰⵜⵉⴳ ⵏ ⵡⴰⵙⵙ)",
    "حجز فوري": "Tasegda ur tura (ⵜⴰⵙⴻⴳⴷⴰ)",
    "سيارات مخصصة للزفاف": "Tikarratin n zzwaj (ⵜⵉⴽⴰⵔⵔⴰⵜⵉⵏ ⵏ ⵣⵣⵡⴰⵊ)",
    "سيارات مميزة من شركائنا الموثوقين": "Tikarratin seg iymen (ⵜⵉⴽⴰⵔⵔⴰⵜⵉⵏ ⵉⵎⴻⵏ)",
    "مستضيف متميز": "Adbab amnay (ⴰⴷⴱⴰⴱ ⴰⵎⵏⴰⵢ)",
    "تأمين حماية شامل بالتعاقد مع درايف RENT للتكافل": "Tadbelt id-Drive RENT (ⵜⴰⴷⴱⴻⵍⵜ ⵉⴷ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "تأمين درايف RENT والوساطة (5%):": "Tadbelt Drive RENT (ⵜⴰⴷⴱⴻⵍⵜ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "مستضيف متميز درايف RENT": "Adbab Drive RENT (ⴰⴷⴱⴰⴱ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "مضيف متميز درايف RENT": "Adbab Drive RENT (ⴰⴷⴱⴰⴱ ⴷⵔⴰⵢف ⵔⴻⵏⵜ)",
    "مضيف متميز • درايف RENT Partner": "Adbab • Drive RENT (ⴰⴷⴱⴰⴱ ⴷⵔⴰⵢⴼ ⵔⴻⵏⵜ)",
    "حجز فوري مؤكد": "Tasegda yules (ⵜⴰⵙⴻⴳⴷⴰ ⵢⵓⵍⴻⵙ)",
    "ناقل حركة أوتوماتيكي": "Automatic (ⴰⵓⵜⵓⵎⴰⵜⵉⴽ)",
    "أوتوماتيك": "Automatique (ⴰⵓⵜⵓⵎⴰⵜⵉⴽ)",
    "يدوي": "Manual (ⵎⴰⵏⵓⴰⵍ)",
    "الوقود": "Fuel (ⵍⵇⵓⴷ)",
    "المحرك": "Moteur (ⵎⵓⵜⴻⵓⵔ)",
    "بنزين": "Essence (ⴻⵙⵙⴻⵏⵛⴻ)",
    "ديزل": "Diesel (ⴷⵉⴻⵙⴻⵍ)",
    "هجين": "Hybrid (ⵀⵢⴱⵔⵉⴷ)",
    "كهربائية": "Electrique (ⴻⵍⴻⵛⵜⵔⵉⵇ)",
    "دج/يوم": "DA/ass (ⴷ.ⵊ/ⴰⵙⵙ)",
    "دج": "DA (ⴷ.ⵊ)",
    "طلب الحجز": "Asuter n tsegda (ⴰⵙⵓⵜⴻⵔ ⵏ ⵜⵙⴻⴳⴷⴰ)",
    "تأكيد الحجز": "Kles tasegda (ⴽⵍⴻⵙ ⵜⴰⵙⴻⴳⴷⴰ)",
    "تأكيد": "Ih (ⵉⵀ / ⴽⵍⴻⵙ)",
    "إلغاء": "Sfeḍ (ⵙⴼⴻⴹ)",
    "تفاصيل السيارة": "Aglam n tkarrat (ⴰⴳⵍⴰm ⵏ ⵜⴽⴰⵔⵔⴰⵜ)",
    "الميزات والمواصفات": "Ifer d ismawen (ⵉⴼⴻⵔ ⴷ ⵉⵙⵎⴰⵡⴻⵏ)",
    "تقييم المضيف": "Udm n udbab (ⵓdm ⵏ ⵓⴷⴱⴰⴱ)",
    "التقييمات": "Imeslayen (ⵉⵎⴻⵙⵍⴰⵢⴻⵏ)",
    "الموقع والاتصال": "Tansa d ungal (ⵜⴰⵏⵙⴰ ⴷ ⵓⵏⴳⴰⵍ)",
    "تحديد تاريخ الكراء": "Fren isura (ⴼⵔⴻⵏ ⵉⵙⵓⵔⴰ)",
    "تاريخ البدء": "Ass n beddu (ⴰⵙⵙ ⵏ ⴱⴻⴷⴷⵓ)",
    "تاريخ الانتهاء": "Ass n tagara (ⴰⵙⵙ ⵏ ⵜⴰⴳⴰⵔⴰ)",
    "السعر الإجمالي": "Atig n uksar (ⴰⵜⵉⴳ)",
    "الوديعة / الكفالة": "Tadbelt (ⵜⴰⴷⴱⴻⵍⵜ)",
    "موقع مكتب الاستعلام": "Buro n usiwel (ⴱⵓⵔⵓ ⵏ ⵓⵙⵉⵡⴻⵍ)",
    "السيارة متوفرة للكراء": "Tella i ukray (ⵜⴻⵍⵍⴰ ⵉ ⵓⴽⵔاي)",
    "السيارة غير متوفرة حالياً": "Ur tella ara tura (ⵓⵔ ⵜⴻⵍⵍⴰ ⴰⵔⴰ ⵜⵓⵔⴰ)",
    "تأكيد الكراء": "Confirm (ⴽⵍⴻⵙ ⵓⴽⵔⴰⵢ)",
    "أيام الكراء الإجمالية:": "Ussan ukray (ⵓⵙⵙⴰⵏ ⵓⴽⵔⴰⵢ : )",
    "سعر كراء السيارة الكلي:": "Atig kray ungal (ⴰⵜⵉⴳ ⵓⴽⵔⴰⵢ : )",
    "تأمين درايف RENT وعمولة الخدمة:": "Tadbelt d ungal (ⵜⴰⴷⴱⴻⵍⵜ ⴷ ⵓⵏⴳⴰⵍ : )",
    "المبلغ الكلي المستحق:": "Atig kll (ⴰⵜⵉⴳ ⴽⵍⵍ : )",
    "الوديعة الضمانية المستردة (تدفع عند الاستلام للوكالة):": "Tadbelt n udbab (ⵜⴰⴷⴱⴻⵍⵜ ⵓⴷⴱⴰⴱ)",
    "مبلغ الوديعة مسترد كلياً فور انتهاء فترة الكراء وثبوت سلامة السيارة.": "Tadbelt d-tettuxellas ur tasegda ufg (ⵜⴰⴷⴱⴻⵍⵜ ⴷ-ⵜⴻⵜⵜⵓⵅⴻⵍⵍⴰⵙ).",
    "الاستمرار وتأكيد الحجز الفوري": "Kles tasegda tura (ⴽⵍⴻⵙ ⵜⴰⵙⴻⴳⴷⴰ ⵜⵓⵔⴰ)",
    "سيارات": "tikarratin",
    "تبدأ من": "beddu seg",
    "يوم": "ass",
    "التصنيف الفئوي": "Tismilin",
    "ناقل السرعات": "Vitesse",
    "عرض الكل": "Af-d akk",
    "عنا": "ɣef-ney",
    "حياك الله": "Ansuf",
    "تقييم": "rating",
    "مشاهدة كافة التعليقات والتقييمات": "Wali akk imedyaten seg ukarat",
    "التقييمات والتعليقات": "Atig d tibratin",
    "بناءً على": "Atig seg",
    "آراء المستأجرين الأخيرة": "Imeslayen n imsafen imaynuten",
    "جاري تحميل المزيد من التقييمات...": "Rǧu imedyaten nniḍen...",
    "تم تحميل كافة التعليقات والتقييمات الموثقة": "Akk imeslayen klsen seg uxlas",
    "اسحب للأعلى لمشاهدة المزيد": "Sali afawet i ufrak nniḍen",
    "Cleanliness": "Zeddeg",
    "Maintenance": "Maintenance",
    "Communication": "Tawa",
    "Convenience": "Sahl",
    "Accuracy": "Nican",

    // Bookings / Trips
    "حجوزاتي": "Tisegdiwin-inu (ⵜⵉⵙⴻⴳⴷⵉⵡِⵉⵏ-ⵉⵏⵓ)",
    "رحلة قادمة": "Imuddu d-yusan (ⵉⵎⵓⴷⴷⵓ ⴷ-ⵢⵓⵙⴰⵏ)",
    "رحلة سابقة": "Imuddu yezrin (ⵉⵎⵓⴷⴷⵓ ⵢⴻⵣⵔⵉⵏ)",
    "حالات الحجز": "Tisuɣlin (ⵜⵉⵙⵓⵖⵍⵉⵏ)",
    "قيد الانتظار": "Rǧu (ⵔⵊⵓ)",
    "مؤكد": "Yules (ⵢⵓⵍⴻⵙ)",
    "ملغي": "Sfeḍ (ⵙⴼⴻⴹ)",
    "نشط": "Yugar (ⵢⵓⴳⴰⵔ)",
    "مكتمل": "Fuk (ⴼⵓⴽ)",
    "كود الحجز:": "Ungal n tsegda:",
    "استعراض العقد": "Afra n ulaɣ (ⴰⴼⵔⴰ ⵏ ⵓⵍⴰⵖ)",
    "تقييم التجربة": "Atig n tsegda (ⴰⵜⵉⴳ)",
    "تواصل مع المضيف": "Siwel i udbab (ⵙⵉⵡⴻⵍ ⵉ ⵓⴷⴱⴰⴱ)",
    "تواصل هاتفي": "Siwel rreft (ⵙⵉⵡⴻⵍ ⵔⵔⴻⴼⵜ)",
    "اتصال": "Siwel (ⵙⵉⵡⴻⵍ)",
    "اكتشف آلاف السيارات المتاحة على درايف RENT واحجز رحلتك القادمة.": "Af-d tiri n tikarratin di Drive RENT.",
    "ملاحظة: هذا اتصال افتراضي ومحاكاة مدمجة داخل تطبيق درايف RENT الجزائر لسهولة تواصل الأعضاء مع الوكالات المعتمدة.": "Ungal virtual di Drive RENT.",
    "تم إلغاء الحجز وسحب الطلب": "Tasegda tyules sfori (ⵜⴰⵙⴻⴳⴷⴰ ⵜⵢⵓⵍⴻⵙ)",
    "نشطة الآن": "Tella tura (ⵜⴻⵍⵍⴰ ⵜⵓⵔⴰ)",
    "قيد معالجة الطلب": "Rǧu tsegda (ⵔⵊⵓ ⵜⵙⴻⴳⴷⴰ)",
    "انتهى الكراء": "Ukray ifuk (ⵓⴽⵔⴰⵢ ⵉⴼⵓⴽ)",
    "كراء مؤكد": "Ukray yules (ⵓⴽراء ⵢⵓⵍⴻⵙ)",
    "تاريخ كراء السيارة:": "Imuddu ukray (ⵉⵎⵓⴷⴷⵓ ⵓⴽⵔⴰⵢ : )",
    "سعر الكراء الكلي:": "Atig kll (ⴰⵜⵉⴳ ⴽⵍⵍ : )",
    "رمز تأكيد الحجز المباشر:": "Ungal n usseg_da (ⵓⵏⴳⴰⵍ : )",
    "تفاصيل عقد كراء مركبة مؤمنة بالمنصة": "Aglam ungal n tkarrat (ⴰⴳⵍⴰⵎ ⵓⵏⴳⴰⵍ ⵜⴽⴰⵔⵔⴰⵜ)",

    // Profile & Account Settings
    "بيانات الحساب": "Isek n umiḍan (ⵉⵙⴻⴽ ⵏ ⵓⵎⵉⴹⴰⵏ)",
    "اسم المضيف / الوكالة بالمنصة": "Issem n udbab (ⵉⵙⵙⴻⵎ ⵏ ⵓdbab)",
    "بريدك الإلكتروني (لتوثيق التعامل الفوري)": "Imayl-inu (ⵉⵎⴰⵢⵍ)",
    "الهاتف للاتصال من المكتتبين": "Ungal udbab (ⵓⵏⴳⴰⵍ ⵓⴷⴱⴰⴱ)",
    "نبذة تعريفية وموقع مكتب الاستعلام": "Gf udbab d tansa (ⵖⴼ ⵓⴷⴱⴰⴱ ⴷ ⵜⴰⵏⵙⴰ)",
    "تم حفظ وتزامن ملف حسابك بشكل فوري آمن بالمنصة.": "Ayen yules di lqanun (ⴰⵢⴻⵏ ⵢⵓⵍⴻⵙ ⴳ ⵍⵇⴰⵏⵓⵏ).",
    "تم حفظ وتزامن ملف حسابك بشكل فوري آمن.": "Ayen yules di lqanun (ⴰⵢⴻⵏ ⵢⵓﻠⴻⵙ ⴳ ⵍⵇⴰⵏⵓⵏ).",
    "أرشيف المعاملات الأخيرة": "Isuraf n umiḍan (ⵉⵙⵓⵔⴰⴼ ⵏ ⵓⵎⵉⴹⴰⵏ)",
    "تنزيل الفاتورة": "Tawa n usuraf (ⵜⴰⵡⴰ ⵏ ⵓⵙⵓⵔⴰⴼ)",
    "شحن المحفظة": "Aɛmar n uqiḍaf (ⴰⵄⵎⴰⵔ ⵏ ⵓⵇⵉⴹⴰⴼ)",
    "رصيد المحفظة الكلي": "Atig n uqiḍaf (ⴰⵜⵉⴳ ⵏ ⵓⵇⵉⴹⴰⴼ)",
    "رصيدك الكلي بالمحفظة:": "Atig di uqiḍaf (ⴰⵜⵉⴳ ⵇⵉⴹⴰⴼ : )",
    "إيداع فوري آمن": "Aɛmar id-yusan (ⴰⵄⵎⴰⵔ ⵢⵓⵍⴻⵙ)",
    "البطاقة الذهبية أو بطاقة CIB": "Kart Edahabia neɣ CIB (ⴽⴰⵔⵜ ⴻⴷⴰⵀⴰⴱⵉⴰ)",
    "توثيق الحساب": "Tagezda ungal (ⵜⴰⴳⴻⵣⴷⴰ ⵓⵏⴳⴰⵍ)",
    "بطاقة التعريف الوطنية": "Taftart ungal (ⵜⴰⴼⵜⴰⵔⵜ ⵓⵏⴳⴰⵍ)",
    "رخة السياقة": "Turagt n ussaf (ⵜⵓⵔⴰⴳⵜ ⵏ ⵓⵙⵙⴰⴼ)",
    "رخصة السياقة": "Turagt n ussaf (ⵜⵓⵔⴰⴳⵜ ⵏ ⵓⵙⵙⴰف)",
    "يرجى توفير ورفع الوثائق المنصوص عليها لتعزيز ثقة المكتتبين وتفعيل الفاتورة التأمينية المعتمدة لواردات كراء السيارات.": "Azen tiferatin n tagezda.",
    "السجل التجاري الجزائري (RC)": "Aruyt RC lzayer (ⴰⵔⵓⵢⵜ ⵔⵛ)",
    "بطاقة التعريف الجبائي (NIF)": "Aruyt NIF lzayer (ⴰⵔⵓيⵜ ⵏⵉⴼ)",
    "دفتر شروط تأمين المركبة الكلي": "Assurance n tkarrat (ⴰⵙⵙⵓⵔⴰⵏⵛⴻ)",
    "تم رفع ملف الورقة الثبوتية بنجاح! يتم التدقيق والتحقق منها وتنشيط حسابك الآن.": "Tagezda tyules! (ⵜⴰⴳⴻⵣⴷⴰ ⵜⵢⵓⵍⴻⵙ).",
    "الملف الشخصي للمضيف": "Udm n udbab (ⵓⴷⵎ ⵏ ⵓⴷⴱⴰⴱ)",
    "مركز الأرباح المالي": "Amas n isuraf (ⴰⵎⴰⵙ ⵏ ⵉⵙⵓⵔⴰⴼ)",
    "الملفات والوثائق القانونية": "Tifliwin n lqanun (ⵜⵉⴼⵍⵉⵡⵉⵏ ⵏ ⵍⵇⴰⵏⵓⵏ)",
    "الإعدادات والخصوصية": "Tiseɣriyين (ⵜⵉⵙⴻⵖⵔⵉⵢⵉⵏ)",
    "تنفيذ طلب الإيداع الفوري": "Kles aɛmar (ⴽⵍⴻⵙ ⴰⵄⵎⴰⵔ)",
    "أدخل قيمة الرصيد المراد إضافته (دج)": "Aru atig n uqiḍaf (DZD)",
    "بوابة الدفع الإلكتروني الجزائرية المقبولة": "Kart di lzayer (ⴽⴰⵔⵜ ⴷⵉ ⵍⵣⴰⵢⴻⵔ)",
    "الرصيد الحالي بالمحفظة:": "Atig tura (ⴰⵜⵉⴳ ⵜⵓⵔⴰ : )",
    "تاريخ التسجيل بالجزائر:": "Ass tgezda (ⴰⵙⵙ ⵜⴳⴻⵣⴷⴰ : )",
    "معلومات الاتصال الموثقة": "Ungal ungal (ⵓⵏⴳⴰⵍ ⵓⵏⴳⴰⵍ)",
    "تعديل الحساب": "Senfel amiḍan (ⵙⴻⵏⴼⴻⵍ ⴰⵎⵉⴹⴰⵏ)",
    "التنبيهات والإشعارات": "Tiseɣriyin tibratin (ⵜⵉⵙⴻⵖⵔⵉⵢⵉⵏ)",
    "تفضيلات ناقل الحركة المفضل": "Vitesse fren (ⴼⵔⴻⵏ ⵡⵉⵜⴻⵙⵙⴻ)",
    "تنبيهات الرسائل والنظام الفورية (SMS)": "Tibratin SMS (ⵜⵉⴱⵔⴰⵜⵉⵏ)",
    "تنبيهات إلكترونية ومستجدات المنصة": "Imayl tibratin (ⵉⵎⴰⵢⵍ)",
    "العقود والمسؤوليات": "Lqanun d tadbelt (ⵍⵇⴰⵏⵓⵏ)",
    "بند العقود القانوني وكفالة السيارات": "Lqanun ukarat (ⵍⵇⴰⵏⵓⵏ ⵜⴽⴰⵔⵔⴰⵜ)",
    "شروط وقوانين المسؤولية المدنية": "Lqanun azar (ⵍⵇⴰⵏⵓⵏ)",
    "تلقي تنبيهات وعوائد الكراء الفورية": "Tibratin f tsegda (ⵜⵉⴱⵔⴰⵜⵉⵏ)",
    "مبارك! لقد تم تسجيل معلومات وكالتك": "Ansuf! Tagezda tyules (ⴰⵏⵙⵓⴼ)",

    // Support Chat
    "الدعم الفني والإستعلام": "Tallelt (ⵜⴰⵍⵍⴻⵍⵜ)",
    "اكتب رسالتك وسيجيبك مرشدنا الآلي فوراً...": "Aru tibratin tura (ⴰⵔⵓ ⵜⵉⴱⵔⴰⵜⵉⵏ ⵜⵓⵔⴰ...)",

    // Host Dashboard / Business
    "الرصيد الكلي المقبوض": "Isuraf akk (ⵉⵙⵓⵔⴰⴼ ⴰⴽⴽ)",
    "مستحقات هذا الأسبوع": "Isuraf wass-a (ⵉⵙⵓⵔⴰⴼ ⵡⴰⵙⵙ-ⴰ)",
    "مبالغ قيد التصفية": "Isuraf n rǧu (ⵉⵙⵓⵔⴰⴼ ⵔⵊⵓ)",
    "نشاطات أسطولك الحالية": "Tikarratin-inu fell (ⵜⵉⴽⴰⵔⵔⴰⵜⵉⵏ-ⵉⵏⵓ)",
    "مستأجر:": "Amsaf (ⴰⵎⵙⴰⴼ : )",
    "إنشاء وكالتك الخاصة": "Kles amiḍan udbab (ⴽⵍⴻⵙ ⴰⵎⵉⴹⴰⵏ)",
    "سجل وكالتك وحقق عوائد مستمرة": "Kles tikarratin kra (ⴽⵍⴻⵙ ⵜⵉⴽⴰⵔⵔⴰⵜⵉⵏ)",
    "خطوات لتصبح مضيفاً": "Amek ara d-iliḍ d udbab",
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageType>(() => {
    const saved = localStorage.getItem("drive_rent_lang");
    if (saved === "en" || saved === "fr" || saved === "ar" || saved === "amazigh") {
      return saved as LanguageType;
    }
    return "ar";
  });

  const setLanguage = (lang: LanguageType) => {
    setLanguageState(lang);
    localStorage.setItem("drive_rent_lang", lang);
  };

  // Is Right-To-Left layout direction. Only Arabic is RTL in our listing.
  const isRtl = language === "ar";
  const dir = isRtl ? "rtl" : "ltr";

  // Global translation function
  const t = (text: string): string => {
    if (!text) return "";
    const cleanSource = text.trim();
    
    // Check if translation exists for target language
    const currentLangDict = dictionary[language];
    if (currentLangDict && currentLangDict[cleanSource]) {
      return currentLangDict[cleanSource];
    }

    // Try a direct sub-string matching fallback for common words in sentences if perfect match is not found
    if (language !== "ar") {
      // For exact matches only to preserve user & car names perfectly, 
      // but let's also allow case-insensitive or punctuation-less lookups
      const keys = Object.keys(currentLangDict || {});
      const lowerClean = cleanSource.toLowerCase();
      const matchedKey = keys.find(k => k.toLowerCase() === lowerClean);
      if (matchedKey && currentLangDict[matchedKey]) {
        return currentLangDict[matchedKey];
      }
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRtl, dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
